"""Recreating migrations

Revision ID: 690ed9b651cc
Revises: 
Create Date: 2025-02-11 19:59:24.321804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690ed9b651cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_results_id'), 'moderation_results', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_results_text'), 'moderation_results', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_results_text'), table_name='moderation_results')
    op.drop_index(op.f('ix_moderation_results_id'), table_name='moderation_results')
    op.drop_table('moderation_results')
    # ### end Alembic commands ###
